"""empty message

Revision ID: 5ed0d1ae183f
Revises: 
Create Date: 2026-09-21 19:05:57.605980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5ed0d1ae183f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discarded_problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('requested_difficulty', sa.Enum('LV1', 'LV2', 'LV3', 'LV4', 'LV5', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('discard_reason', sa.Enum('STATIC_VALIDATION', 'DIFFICULTY_MISMATCH', 'DUPLICATE', 'EXAMPLE_MISMATCH', 'REFERENCE_CODE_FAILED', 'LLM_ERROR', name='discardreason', native_enum=False, length=32), nullable=False),
    sa.Column('discard_detail', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discarded_problems_discard_reason'), 'discarded_problems', ['discard_reason'], unique=False)
    op.create_index(op.f('ix_discarded_problems_requested_category'), 'discarded_problems', ['requested_category'], unique=False)
    op.create_table('fewshot_seeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'PROMOTED', name='seedsource', native_enum=False, length=32), nullable=False),
    sa.Column('category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('LV1', 'LV2', 'LV3', 'LV4', 'LV5', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('input_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fewshot_lookup', 'fewshot_seeds', ['category', 'difficulty', 'is_active'], unique=False)
    op.create_table('generated_problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_difficulty', sa.Enum('LV1', 'LV2', 'LV3', 'LV4', 'LV5', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('LV1', 'LV2', 'LV3', 'LV4', 'LV5', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('category_select_reason', sa.Text(), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('input_format', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Text(), nullable=False),
    sa.Column('input_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden_test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hint_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_problems_category'), 'generated_problems', ['category'], unique=False)
    op.create_index('ix_generated_problems_pending', 'generated_problems', ['category', 'difficulty'], unique=False, postgresql_where=sa.text('sent_at IS NULL'))
    op.create_table('problem_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('algorithm_core', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['generated_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id')
    )
    op.create_index(op.f('ix_problem_embeddings_category'), 'problem_embeddings', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_embeddings_category'), table_name='problem_embeddings')
    op.drop_table('problem_embeddings')
    op.drop_index('ix_generated_problems_pending', table_name='generated_problems', postgresql_where=sa.text('sent_at IS NULL'))
    op.drop_index(op.f('ix_generated_problems_category'), table_name='generated_problems')
    op.drop_table('generated_problems')
    op.drop_index('ix_fewshot_lookup', table_name='fewshot_seeds')
    op.drop_table('fewshot_seeds')
    op.drop_index(op.f('ix_discarded_problems_requested_category'), table_name='discarded_problems')
    op.drop_index(op.f('ix_discarded_problems_discard_reason'), table_name='discarded_problems')
    op.drop_table('discarded_problems')
    # ### end Alembic commands ###
