"""add trigger and sent_at to battle_problems

Revision ID: 88bb96af4ad1
Revises: afe6f63cc34a
Create Date: 2026-09-27 23:58:14.373064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bb96af4ad1'
down_revision: Union[str, Sequence[str], None] = 'afe6f63cc34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 행은 API로 만든 것이라 ON_DEMAND로 채워지고 전송 대상에서 빠진다.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_problems', sa.Column('trigger', sa.Enum('BATCH', 'ON_DEMAND', name='trigger', native_enum=False, length=32), server_default='ON_DEMAND', nullable=False))
    op.add_column('battle_problems', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battle_problems', 'sent_at')
    op.drop_column('battle_problems', 'trigger')
    # ### end Alembic commands ###
