"""add trigger and purpose to generated_problems

Revision ID: afe6f63cc34a
Revises: d58830c52060
Create Date: 2026-09-26 23:53:30.244989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe6f63cc34a'
down_revision: Union[str, Sequence[str], None] = 'd58830c52060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 행은 배치가 생기기 전에 API로 만든 것이라 ON_DEMAND/NORMAL로 채워지고 전송 대상에서 빠진다.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_problems', sa.Column('trigger', sa.Enum('BATCH', 'ON_DEMAND', name='trigger', native_enum=False, length=32), server_default='ON_DEMAND', nullable=False))
    op.add_column('generated_problems', sa.Column('purpose', sa.Enum('NORMAL', 'DAILY', name='problempurpose', native_enum=False, length=32), server_default='NORMAL', nullable=False))
    op.drop_index(op.f('ix_generated_problems_pending'), table_name='generated_problems', postgresql_where='(sent_at IS NULL)')
    op.create_index('ix_generated_problems_pending', 'generated_problems', ['purpose', 'category', 'difficulty'], unique=False, postgresql_where=sa.text("sent_at IS NULL AND trigger = 'BATCH'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_problems_pending', table_name='generated_problems', postgresql_where=sa.text("sent_at IS NULL AND trigger = 'BATCH'"))
    op.create_index(op.f('ix_generated_problems_pending'), 'generated_problems', ['category', 'difficulty'], unique=False, postgresql_where='(sent_at IS NULL)')
    op.drop_column('generated_problems', 'purpose')
    op.drop_column('generated_problems', 'trigger')
    # ### end Alembic commands ###
