"""empty message

Revision ID: d4ad00459a5e
Revises: 5ed0d1ae183f
Create Date: 2026-09-22 14:53:52.637707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ad00459a5e'
down_revision: Union[str, Sequence[str], None] = '5ed0d1ae183f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fewshot_seeds', sa.Column('problem_content', sa.Text(), nullable=False))
    op.drop_column('fewshot_seeds', 'problem_description')
    op.add_column('generated_problems', sa.Column('problem_content', sa.Text(), nullable=False))
    op.drop_column('generated_problems', 'problem_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_problems', sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('generated_problems', 'problem_content')
    op.add_column('fewshot_seeds', sa.Column('problem_description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('fewshot_seeds', 'problem_content')
    # ### end Alembic commands ###
