"""empty message

Revision ID: d58830c52060
Revises: d4ad00459a5e
Create Date: 2026-09-23 01:30:26.022778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58830c52060'
down_revision: Union[str, Sequence[str], None] = 'd4ad00459a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fewshot_seeds', sa.Column('source_ref', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fewshot_seeds', 'source_ref')
    # ### end Alembic commands ###
