"""add battle_problems and battle_problem_embeddings

Revision ID: ece5883a8359
Revises: d58830c52060
Create Date: 2026-09-27 02:30:59.866198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ece5883a8359'
down_revision: Union[str, Sequence[str], None] = 'd58830c52060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle_problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=False),
    sa.Column('problem_content', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_problems_category'), 'battle_problems', ['category'], unique=False)
    op.create_table('battle_problem_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('battle_problem_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RANDOM', 'ARRAY', 'STRING', 'DP', 'GRAPH', 'TREE', 'STACK_QUEUE', 'BINARY_SEARCH', 'GREEDY', 'BACKTRACKING', 'TWO_POINTER', 'HASH_TABLE', 'HEAP', 'SORTING', 'IMPLEMENTATION', 'BRUTE_FORCE', 'MATH', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('algorithm_core', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battle_problem_id'], ['battle_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('battle_problem_id')
    )
    op.create_index(op.f('ix_battle_problem_embeddings_category'), 'battle_problem_embeddings', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_battle_problem_embeddings_category'), table_name='battle_problem_embeddings')
    op.drop_table('battle_problem_embeddings')
    op.drop_index(op.f('ix_battle_problems_category'), table_name='battle_problems')
    op.drop_table('battle_problems')
    # ### end Alembic commands ###
